[workspace]

members = [
  "crates/astria-conductor",
  "crates/astria-conductor-test",
  "crates/execution-apis",
  "crates/gossipnet",
  "crates/rs-cnc",
  "crates/sequencer-relayer",
  "crates/sequencer-relayer-proto",
  "crates/sequencer-relayer-test",
]
