[package]
name = "sequencer-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rs-cnc = { git = "https://github.com/astriaorg/rs-cnc.git" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24.2"}